### ISSUE TITLE
Update timestamp only if there are other changes

### ISSUE THREAD

**Issue by sharpner** [UnnoTed/fileb0x#18]
Hi! 

Is there a way to make the asset generation idempotent so that it won't update the timestamp in the assets file if there are no other changes within the data?

My configuration looks like this:
```yaml                                                                                                    
pkg: assets
dest: "."
fmt: true
output: assets.go
updater:
  enabled: false
custom:
  - files:
    - "./data/*.jpeg"
    base: "./data/"
```
