### ISSUE TITLE
"prefix" bugs?

### ISSUE THREAD

**Issue by iu0v1** [UnnoTed/fileb0x#8]
Hey.

Has faced with several problems.

#### First
In attempt to use such configuration - I receive strange behavior. First dot in filenames will be replaced with a `prefix` var.
```
custom:
  - files:
    - "./main.go"
    - "./fileb0x.yaml"
    base: "./"
    prefix: "_bug?_"
```

#### Second

The `prefix` option doesn't work for me :(
```
  - files:
    - "./static"
    prefix: "test_prefix/"
```

#### Result:

![fileb0x](https://cloud.githubusercontent.com/assets/1669027/24071415/c55986be-0bd9-11e7-91a1-52e259087611.png)
