### ISSUE TITLE
"Base" option stopped working

### ISSUE THREAD

**Issue by andreynering** [UnnoTed/fileb0x#9]
Hi,

Seems that https://github.com/UnnoTed/fileb0x/commit/5494112a4d3e8629069278b3b0125960cd699c8d changes the behavior of `base`.

I have something like this:

```yml
custom:
  - files:
    - "public/js"
    - "public/css"
    base: "public/"
```

Before that commit, I could serve files as `/js/...` and `/css/...` instead of `/public/js/`. But now `public/` is not being removed from the path anymore.

Thanks for this awesome lib.
